defaults:
  - _self_
  - mode: text2img
  - model: sdxl_base
  - controlnet: disabled

prompt: ""
negative_prompt: null
output: ""
seed: 42
image: null
mask_image: null
device: auto
enable_xformers: false
enable_channels_last: false
hydra:
  run:
    dir: .
  output_subdir: null
  job:
    chdir: false
